### ISSUE TITLE
[FEAT] 화자분리 모델들 테스트 후 음성노이즈 제거에 효과가있을지 판단

### ISSUE THREAD

**Issue by kwonbooyeon** [kookmin-sw/capstone-2024-24#20]
## 작업 내용
화자분리 모델들 테스트 후 화자분리뿐 아니라 **음성노이즈 제거**에 효과가있을지 판단

기대 효과 : 음성파일 처리과정(.py)을 제거함으로써 안드로이드 외부 언어 코드로 인한 안드로이드 부담 줄이기..

## 일정
예상 시작일: 2024-04-05
예상 소요일: 3일 이내

## 체크리스트
- [x] 화자분리 오픈소스들 뜯어보기.
- [x] 가능성 높은 모델 테스트
- [x] 결과 확인

**Comment by kwonbooyeon** [comment]
테스트용 음성을 구하기 쉽지않음.. 만들기도 또한 쉽지않음 평일이 되서 따로 녹음한 후 다시 테스트 진행 예정

**Comment by kwonbooyeon** [comment]
stream이 지원이 되는 듯한 diart를 가장 유력하게 다뤄보고 싶지만 이것도 pyannote기반이라 pyannote의 결과가 중요한데.
간단한 테스트에서는 어느정도 분리하는 모습을 보여주었지만 이게 단순히 가장 분명하고 큰 소리 사람의 소리를 인식해서 자른건지 음성 자체를 분리해냈다고 볼수있을지 확신이 서지않음

**Comment by kwonbooyeon** [comment]
전자의 경우를  Speaker Diarization, 후자의 경우를 Speaker Seperation라고 하는데. 우리가 필요한건 후자의 화자 분리. 
관련 모델로 다시 모으는 중.
기능 자체는 잘 작동하나 실시간이 가능한지 속도는 어떤지 확인해야함.

**Comment by kwonbooyeon** [comment]
가능한 모델을  찾긴했으나 stream이.. vad도 오픈소스 모델로 찾아보기로함.

**Comment by kwonbooyeon** [comment]
이론적으로는 가능하나 실제 적용가능한지를 판단하기에 힘이 듬... 현재 svoice test중이나 쉽지않음. 시간이 더걸릴것같음... pretrained weight를 찾았으나 model load에 에러가 있음... 실제 적용가능할지 자신할 수 없음. 가능한 이 방법을 쓰나 잘 안된다면 차선책으로 둬야할듯

**Comment by devkaspee** [comment]
**결론 - 일단 차선책으로 미루고, 당장은 적용하지 말자**
평균 7.5초 정도의 [2ch mixed voice file](https://github.com/facebookresearch/svoice/tree/main/dataset/debug/mix)을 처리할 때, apple m1 CPU 기준 파일당 9.8초정도 소요. GPU를 쓰면 성능이 좋아질 여지가 있으나 아직 미지수인 상황이고, Vad, LLM과 whisper 자체의 레이턴시까지 포함하면 end-to-end 응답시간이 길 것으로 판단함.

우선 vad -> whisper까지만 잘 구현해보는 것으로 하고 issue close할까요? @kwonbooyeon

**Comment by kwonbooyeon** [comment]
noise 감소에는 충분한 성능이 보이나 속도문제로 인해 일단 이 문제는 보류하기로  결정. 안드로이드의 python file 돌리기 필요할지는 프로토 타입완성후 결정하기로 결정
